--liquibase formatted sql

--changeset author001:001-create-dev-sample
create table DEV_APP.dev_sample (
    id bigint generated by default as identity primary key,
    name varchar(100) not null
);

--changeset author001:002-insert-dev-sample
insert into DEV_APP.dev_sample (name) values ('dev example');
