spring.application.name=liquibase-app
spring.liquibase.enabled=false

app.datasource.dev.url=jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS DEV_APP\\;CREATE SCHEMA IF NOT EXISTS DEV_LIQUIBASE
app.datasource.dev.driver-class-name=org.h2.Driver
app.datasource.dev.username=sa
app.datasource.dev.password=

app.datasource.integration.url=jdbc:h2:mem:integrationdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS INTERGRATION_APP\\;CREATE SCHEMA IF NOT EXISTS INTERGRATION_LIQUIBASE
app.datasource.integration.driver-class-name=org.h2.Driver
app.datasource.integration.username=sa
app.datasource.integration.password=
