--liquibase formatted sql

--changeset author001:001-create-integration-sample
create table INTERGRATION_APP.integration_sample (
    id bigint generated by default as identity primary key,
    name varchar(100) not null
);

--changeset author001:002-insert-integration-sample
insert into INTERGRATION_APP.integration_sample (name) values ('integration example');
